auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: greatjzy.github.com
url: http://greatjzy.github.com
feed: /atom.xml
author_info: <a href="http://greatjzy.github.com/">greatjzy</a>
